[package]
name = "reflex"
version = "0.1.1"
description = "A minimal flex-like lexer"
license = "MIT"
repository = "https://github.com/nazek42/reflex"
authors = ["bkul"]

[dependencies]
regex = "0.2"
